# Generated by Django 2.2.3 on 2019-07-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20190720_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcredential',
            name='password',
        ),
    ]
