# Generated by Django 2.2.3 on 2019-11-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_remove_toolcredential_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolcredential',
            name='token',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='toolcredential',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
